
import type { Product, Category, ProductPrice } from './types';

export const categories: Category[] = [
  { id: '1', name: 'Classic Attars', slug: 'classic-attars' },
  { id: '2', name: 'Floral Scents', slug: 'floral-scents' },
  { id: '3', name: 'Woody Notes', slug: 'woody-notes' },
  { id: '4', name: 'Limited Edition', slug: 'limited-edition' },
  { id: '5', name: 'Spicy & Exotic', slug: 'spicy-exotic' },
  { id: '6', name: 'Signature Blends', slug: 'signature-blends' },
];

const defaultSizes: ProductPrice[] = [
  { size: '3ml', price: 0 }, // Base price will be overridden
  { size: '6ml', price: 0 },
  { size: '8ml', price: 0 },
  { size: '12ml', price: 0 },
];

// Helper to generate example prices based on a base price for 3ml
const generatePrices = (basePrice: number): ProductPrice[] => [
  { size: '3ml', price: basePrice },
  { size: '6ml', price: parseFloat((basePrice * 1.8).toFixed(2)) }, // Example pricing logic
  { size: '8ml', price: parseFloat((basePrice * 2.3).toFixed(2)) },
  { size: '12ml', price: parseFloat((basePrice * 3.0).toFixed(2)) },
];


export const products: Product[] = [
  {
    id: 'p1',
    name: 'Ak 47',
    description: 'Experience the captivating aroma of Ak 47.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Ak 47. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(20.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://images.unsplash.com/photo-1535683577427-740aaac4ec25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxwZXJmdW1lfGVufDB8fHx8MTc0OTUzNjYzOXww&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'attar bottles',
    featured: true,
    rating: 5,
    isNewArrival: true,
    highlightedNewAttar: true,
  },
  {
    id: 'p2',
    name: 'Al khalij',
    description: 'Experience the captivating aroma of Al khalij.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Al khalij. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(21.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://images.unsplash.com/photo-1520537867678-1253af0c55ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8Z2xhc3MlMjBib3R0bGV8ZW58MHx8fHwxNzQ5NTUzNzY3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'perfume',
    featured: true,
    rating: 4,
    isNewArrival: true,
    highlightedNewAttar: true, // Added to marquee
  },
  {
    id: 'p3',
    name: 'Ameer al oudh',
    description: 'Experience the captivating aroma of Ameer al oudh.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Ameer al oudh. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(22.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://images.unsplash.com/photo-1612784641667-365798bba014?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMXx8YXR0YXJ8ZW58MHx8fHwxNzQ5NTUzNjU3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'perfume bottle',
    featured: true,
    rating: 5,
    isNewArrival: false,
    highlightedNewAttar: true, // Added to marquee
  },
  {
    id: 'p4',
    name: 'Arabian safari',
    description: 'Experience the captivating aroma of Arabian safari.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Arabian safari. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(23.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://images.unsplash.com/photo-1646149757906-e6e9e9a7c77f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxwZXJmdW1yJTIwYXR0YXJ8ZW58MHx8fHwxNzQ5NTUzNzQyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'perfume bottle',
    featured: true,
    rating: 4,
    isNewArrival: false,
  },
  {
    id: 'p5',
    name: 'Arbi',
    description: 'Experience the captivating aroma of Arbi.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Arbi. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(24.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://images.unsplash.com/photo-1646149757906-e6e9e9a7c77f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw4fHxwZXJmdW1yJTIwYXR0YXJ8ZW58MHx8fHwxNzQ5NTUzNzQyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
    isNewArrival: true,
    highlightedNewAttar: true,
  },
  {
    id: 'p6',
    name: 'Aseel',
    description: 'Experience the captivating aroma of Aseel.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Aseel. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(25.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
    isNewArrival: false,
  },
  {
    id: 'p7',
    name: 'Bakhoor',
    description: 'Experience the captivating aroma of Bakhoor.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Bakhoor. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(26.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
    isNewArrival: true,
    highlightedNewAttar: true, // Added to marquee
  },
  {
    id: 'p8',
    name: 'Black musk',
    description: 'Experience the captivating aroma of Black musk.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Black musk. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(27.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p9',
    name: 'Black oudh',
    description: 'Experience the captivating aroma of Black oudh.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Black oudh. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(28.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p10',
    name: 'Black rose',
    description: 'Experience the captivating aroma of Black rose.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Black rose. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(29.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p11',
    name: 'Blue jeans',
    description: 'Experience the captivating aroma of Blue jeans.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Blue jeans. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(30.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p12',
    name: 'Chocolate',
    description: 'Experience the captivating aroma of Chocolate.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Chocolate. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(31.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p13',
    name: 'Cr-7',
    description: 'Experience the captivating aroma of Cr-7.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Cr-7. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(32.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p14',
    name: 'Dana',
    description: 'Experience the captivating aroma of Dana.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Dana. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(33.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p15',
    name: 'Darbar',
    description: 'Experience the captivating aroma of Darbar.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Darbar. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(34.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p16',
    name: 'Dove',
    description: 'Experience the captivating aroma of Dove.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Dove. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(35.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p17',
    name: 'Fantasia',
    description: 'Experience the captivating aroma of Fantasia.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Fantasia. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(36.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p18',
    name: 'Fk',
    description: 'Experience the captivating aroma of Fk.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Fk. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(37.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p19',
    name: 'France 2000',
    description: 'Experience the captivating aroma of France 2000.',
    longDescription: 'Indulge in the distinct and memorable fragrance of France 2000. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(38.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p20',
    name: 'Galib',
    description: 'Experience the captivating aroma of Galib.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Galib. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(39.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
  {
    id: 'p21',
    name: 'Green ajmeri',
    description: 'Experience the captivating aroma of Green ajmeri.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Green ajmeri. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(40.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 5,
  },
  {
    id: 'p22',
    name: 'Green sto',
    description: 'Experience the captivating aroma of Green sto.',
    longDescription: 'Indulge in the distinct and memorable fragrance of Green sto. This attar is carefully crafted to offer a unique olfactory experience, perfect for those who appreciate fine scents and desire a touch of personal elegance.',
    prices: generatePrices(41.00),
    categorySlug: 'signature-blends',
    imageUrl: 'https://placehold.co/600x400.png',
    imageHint: 'perfume bottle',
    featured: false,
    rating: 4,
  },
];

export const getProductById = (id: string): Product | undefined => products.find(p => p.id === id);

export const getProductsByCategory = (slug: string): Product[] => products.filter(p => p.categorySlug === slug);

export const getFeaturedProducts = (): Product[] => products.filter(p => p.featured).sort((a, b) => (b.rating || 0) - (a.rating || 0));

export const getNewArrivals = (): Product[] => products.filter(p => p.isNewArrival).sort((a,b) => a.name.localeCompare(b.name));

export const getHighlightedNewAttars = (): Product[] => products.filter(p => p.highlightedNewAttar).sort((a,b) => a.name.localeCompare(b.name));

